name: CI Pipeline

on:
    push:
        branches: [ main ]
        tags: [ '*' ]
    pull_request:

env:
    PHP_VERSION: 8.3

jobs:
    build-macos:
        name: Build macOS
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION }}
                  tools: box

            - name: Castor cache
              uses: actions/cache@v4
              id: cache-castor-macos
              with:
                  path: /Users/runner/.cache/castor
                  key: castor-macos:php-${{ env.PHP_VERSION }}-${{ github.sha }}
                  restore-keys: castor-macos:php-${{ env.PHP_VERSION }}-

            - name: "Install brew formula"
              run: brew install automake

            - uses: "ramsey/composer-install@v3"

            - uses: ./.github/actions/build
              with:
                  repack_os: darwin
                  compile_os: macos
                  php: ${{ env.PHP_VERSION }}

    build-linux:
        name: Build Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION }}
                  tools: box

            - name: Castor cache
              uses: actions/cache@v4
              id: cache-castor-linux
              with:
                  path: /home/runner/.cache/castor
                  key: castor-linux:php-${{ env.PHP_VERSION }}-${{ github.sha }}
                  restore-keys: castor-linux:php-${{ env.PHP_VERSION }}-

            - uses: "ramsey/composer-install@v3"

            - uses: ./.github/actions/build
              with:
                  repack_os: linux
                  compile_os: linux
                  php: ${{ env.PHP_VERSION }}

#    release-artifacts:
#        name: Release artifacts
#        runs-on: ubuntu-latest
#        needs: [ build-macos, build-linux ]
#        if: startsWith(github.ref, 'refs/tags/')
#        steps:
#            -   name: Download artifacts
#                uses: actions/download-artifact@v4
#                with:
#                    path: ./artifacts
#            -   run: tree ./artifacts
#                shell: bash
#            -   name: Upload files to the release
#                uses: softprops/action-gh-release@v1
#                with:
#                    files: |
#                        ./artifacts/test.linux/test.linux
#                        ./artifacts/test.linux.phar/test.linux.phar
#                        ./artifacts/test.darwin/test.darwin
#                        ./artifacts/test.darwin.phar/test.darwin.phar